#=============================================================================
# dark_powered.toml --- dark powered configuration example for SpaceVim
# Copyright (c) 2016-2017 Wang Shidong & Contributors
# Author: Wang Shidong < wsdjeg at 163.com >
# URL: https://spacevim.org
# License: GPLv3
#=============================================================================

# All SpaceVim option below [option] section
[options]
    # set spacevim theme. by default colorscheme layer is not loaded,
    # if you want to use more colorscheme, please load the colorscheme
    # layer
    colorscheme = "gruvbox"
    background = "dark"
    # Disable guicolors in basic mode, many terminal do not support 24bit
    # true colors
    enable_guicolors = true
    # Disable statusline separator, if you want to use other value, please
    # install nerd fonts
    statusline_separator = "arrow"
    statusline_inactive_separator = "arrow"
    buffer_index_type = 4
    enable_tabline_filetype_icon = true
    enable_statusline_display_mode = false
    default_indent = 8
    # layer chinese opt for enable chinese docs
    vim_help_language = "cn"

[[layers]]
name = "chinese"

[[layers]]
name = "denite"

[[layers]]
name = "colorscheme"

[[layers]]
name = 'github'

[[layers]]
name = 'git'

[[layers]]
name = "VersionControl"

[[layers]]
name = "format"

[[layers]]
name = 'shell'
default_position = 'bottom'
default_height = 20

[[layers]]
name = 'lang#markdown'
enableWcwidth = 1
listItemIndent = 1

[[layers]]
name = "lang#python"

[[layers]]
name = "lang#c"

[[layers]]
name = "lang#go"

[[layers]]
name = "lsp"
filetypes = [
    "python",
    "go"
]
